language: node_js
dist: trusty
sudo: false  # See http://docs.travis-ci.com/user/trusty-ci-environment/
node_js:
  - "4"
python:
  - "2.7"
notifications:
  webhooks:
    - http://savage.nonblocking.io:8080/savage/travis
before_install:
  - export DISPLAY=:99.0
  - unset _JAVA_OPTIONS  # JVM heap sizes break closure compiler. #11203.
  - sh -e /etc/init.d/xvfb start
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - mkdir "${TRAVIS_BUILD_DIR}/chrome"
  - dpkg -x google-chrome-stable_current_amd64.deb "${TRAVIS_BUILD_DIR}/chrome"
  - export CHROME_BIN="${TRAVIS_BUILD_DIR}/chrome/opt/google/chrome/google-chrome"
before_script:
  - pip install --user protobuf
  - gem install percy-capybara phantomjs poltergeist
  # Poltergeist requires an absolute path to find phantomjs. See #10305.
  - export PATH="`pwd`/node_modules/.bin:$PATH"
script: node build-system/pr-check.js
branches:
  only:
    - master
    - release
    - canary
    - /^amp-release-.*$/
env:
  global:
    - SAUCE_USERNAME="amphtml"
    - NPM_CONFIG_PROGRESS="false"
  matrix:
    - BUILD_SHARD="pre_build_checks_and_unit_tests"
    - BUILD_SHARD="integration_tests"
cache:
  directories:
  - node_modules
  - .gem
  pip: true
  bundler: true
